# use ruby version 2.2.1
language: ruby
rvm:
- 2.2.1

# skip ruby-oci8 install on travis, since we can't install on travis
bundler_args: --without development production

# setup the database
before_script:
  - psql -c 'create database study_finder_test' -U postgres
  - cp config/database.yml.travis config/database.yml 
  - RAILS_ENV=test bundle exec rake db:migrate

# run the spec test
script:
  - bundle exec rspec

# cache the bundler for the next run
cache: bundler

# launch postgresql on startup
services:
  - postgresql

# have travis not email after every update
notification:
  email: false
